using System.Globalization;

namespace CyberErp.Hrms.App.Common
{
    /// <summary>
    /// Ethiopian (Ge'ez) ↔ Gregorian calendar conversion, for documents rendered server-side.
    /// </summary>
    /// <remarks>
    /// <para>A direct port of the SPA's <c>components/util/ethiopianDate.ts</c>, algorithm for
    /// algorithm. ⚠️ That is deliberate and the two must stay in step: a letter generated by the
    /// server and a date shown beside it in the UI have to name the same day, and two independent
    /// implementations of a calendar drift at exactly the edges nobody tests — Pagume, and the
    /// leap year.</para>
    ///
    /// <para>The Julian Day Number is the pivot: Gregorian by Fliegel–Van Flandern, Ethiopian from
    /// the Amete Mihret epoch (Meskerem 1, year 1 = JDN 1724221). Ethiopian leap years are those
    /// where <c>year % 4 == 3</c>, which give Pagume a sixth day.</para>
    ///
    /// <para>⚠️ .NET ships <see cref="EthiopicCalendar"/>, which is NOT used here. It agrees on the
    /// arithmetic but not on the era handling, and adopting it would make the server and the SPA
    /// two different implementations again — the one thing this port exists to avoid.</para>
    /// </remarks>
    public static class EthiopianDate
    {
        /// <summary>JDN of Meskerem 1, year 1 (Amete Mihret).</summary>
        private const int EthiopicEpoch = 1724221;

        /// <summary>Ge'ez month names, Meskerem first. Index 12 is Pagume, the 13th month.</summary>
        public static readonly string[] MonthsGeez =
        [
            "መስከረም", "ጥቅምት", "ኅዳር", "ታኅሣሥ", "ጥር", "የካቲት", "መጋቢት",
            "ሚያዝያ", "ግንቦት", "ሰኔ", "ሐምሌ", "ነሐሴ", "ጳጉሜ"
        ];

        /// <summary>Transliterated month names, for a Latin-script rendering of an E.C. date.</summary>
        public static readonly string[] MonthsLatin =
        [
            "Meskerem", "Tikimt", "Hidar", "Tahsas", "Tir", "Yekatit", "Megabit",
            "Miazia", "Ginbot", "Sene", "Hamle", "Nehase", "Pagume"
        ];

        public readonly record struct Parts(int Year, int Month, int Day);

        public static bool IsLeapYear(int year) => year % 4 == 3;

        /// <summary>Days in an Ethiopian month — 30, except Pagume's 5 (6 in a leap year).</summary>
        public static int MonthLength(int year, int month) =>
            month == 13 ? (IsLeapYear(year) ? 6 : 5) : 30;

        public static Parts FromGregorian(DateTime date) =>
            JdnToEthiopic(GregorianToJdn(date.Year, date.Month, date.Day));

        /// <summary>
        /// An Ethiopian date written the way a formal letter writes it: <c>ታኅሣሥ 22, 2002 ዓ.ም</c>.
        /// </summary>
        /// <param name="geez">Ge'ez month names when true, transliterated when false.</param>
        public static string Format(DateTime date, bool geez = true)
        {
            var p = FromGregorian(date);
            var month = (geez ? MonthsGeez : MonthsLatin)[p.Month - 1];
            // ዓ.ም (Amete Mihret) marks the era, the way "A.D." would. Without it a bare 2002 beside
            // a Gregorian 2010 in the next column reads as a mistake rather than another calendar.
            return geez
                ? $"{month} {p.Day}, {p.Year} ዓ.ም"
                : string.Create(CultureInfo.InvariantCulture, $"{month} {p.Day}, {p.Year} E.C.");
        }

        private static int GregorianToJdn(int y, int m, int d)
        {
            var a = (14 - m) / 12;
            var yy = y + 4800 - a;
            var mm = m + 12 * a - 3;
            return d + (153 * mm + 2) / 5 + 365 * yy + yy / 4 - yy / 100 + yy / 400 - 32045;
        }

        private static Parts JdnToEthiopic(int jdn)
        {
            var n = jdn - EthiopicEpoch;    // 0-based days since Meskerem 1, year 1
            var cycle = (int)Math.Floor(n / 1461.0);
            var r = n - cycle * 1461;       // day within the 4-year cycle (0..1460)

            // Days per year within a cycle: 365, 365, 366 (the leap year is year%4==3), 365.
            var (yearInCycle, dayOfYear) = r switch
            {
                < 365 => (0, r),
                < 730 => (1, r - 365),
                < 1096 => (2, r - 730),
                _ => (3, r - 1096)
            };

            return new Parts(
                Year: cycle * 4 + 1 + yearInCycle,
                Month: dayOfYear / 30 + 1,
                Day: dayOfYear % 30 + 1);
        }
    }
}
