const parameterInitialData = {
  skip: 0,
  take: 15,
  sortCol: "createdAt",
  dir: "desc",
  searchText: "",
  reportName: "",
  fromDate: "",
  toDate: "",
  customerId: "",
  bankId: "",
  itemId: "",
  salesPersonId: "",
  category: "",
  salesType: "",
  purchaseType: "",
  supplierId: "",
  itemCategoryId: "",
  voucherType: "",
  remainingOnly: false,
  isRoot: false,
  storeId: "",
  expenseTypeId: "",
  groupId: "",
  categoryId: "",
  itemType: "",
  status: "",
  employeeId: "",
  unitId: "",
  pettyCashId: "",
  dateRangeType: "",
  getByFinalStatus:false,
  reportCategory:""

};
export { parameterInitialData };
