using CyberErp.Hrms.App.Common;

namespace CyberErp.Hrms.Tests.Documents;

/// <summary>
/// The Ethiopian calendar, as the bilingual experience letter prints it.
/// </summary>
/// <remarks>
/// ⚠️ This is a PORT of the SPA's <c>ethiopianDate.ts</c>, and the two must not drift: a letter
/// generated by the server and a date shown beside it in the UI have to name the same day. The
/// anchors below are the pairs the frontend implementation is itself verified against, so a
/// divergence in either direction fails here.
/// </remarks>
public class EthiopianDateTests
{
    private static EthiopianDate.Parts Of(int y, int m, int d) =>
        EthiopianDate.FromGregorian(new DateTime(y, m, d));

    // ---- known pairs ---------------------------------------------------------------------

    /// <summary>Ethiopian new year: Meskerem 1 falls on 11 September in an ordinary year.</summary>
    [Fact]
    public void EthiopianNewYearIsMeskerem1()
    {
        var p = Of(2025, 9, 11);

        Assert.Equal(2018, p.Year);
        Assert.Equal(1, p.Month);
        Assert.Equal(1, p.Day);
    }

    /// <summary>…and on 12 September in the year before an Ethiopian leap year.</summary>
    [Fact]
    public void NewYearShiftsToSeptember12BeforeALeapYear()
    {
        var p = Of(2023, 9, 12);

        Assert.Equal(2016, p.Year);
        Assert.Equal(1, p.Month);
        Assert.Equal(1, p.Day);
    }

    /// <summary>The worked example from the feature request: 01 Jan 2010 → Tahsas 23, 2002.</summary>
    [Fact]
    public void TheLetterExampleConverts()
    {
        var p = Of(2010, 1, 1);

        Assert.Equal(2002, p.Year);
        Assert.Equal(4, p.Month);    // Tahsas
        Assert.Equal(23, p.Day);
    }

    [Theory]
    [InlineData(2026, 9, 29, 2019, 1, 19)]    // today, as this was written
    [InlineData(2016, 2, 28, 2008, 6, 20)]
    [InlineData(2012, 12, 31, 2005, 4, 22)]
    public void ConvertsKnownPairs(int gy, int gm, int gd, int ey, int em, int ed)
    {
        var p = Of(gy, gm, gd);

        Assert.Equal((ey, em, ed), (p.Year, p.Month, p.Day));
    }

    // ---- Pagume and leap years ------------------------------------------------------------

    /// <summary>⚠️ Pagume is the 13th month and has 5 days — 6 in a leap year.</summary>
    [Fact]
    public void PagumeHasFiveDaysOrSixInALeapYear()
    {
        Assert.Equal(5, EthiopianDate.MonthLength(2018, 13));
        Assert.Equal(6, EthiopianDate.MonthLength(2019, 13));   // 2019 % 4 == 3
        Assert.Equal(30, EthiopianDate.MonthLength(2018, 1));
    }

    [Fact]
    public void LeapYearsAreThoseWhereYearMod4Is3()
    {
        Assert.True(EthiopianDate.IsLeapYear(2015));
        Assert.True(EthiopianDate.IsLeapYear(2019));
        Assert.False(EthiopianDate.IsLeapYear(2018));
    }

    /// <summary>A date landing in Pagume must report month 13, not roll into the next year.</summary>
    [Fact]
    public void ADateInPagumeReportsMonth13()
    {
        var p = Of(2025, 9, 8);   // a few days before the new year

        Assert.Equal(13, p.Month);
        Assert.Equal(2017, p.Year);
    }

    /// <summary>The sixth of Pagume exists only in a leap year, and must be reachable.</summary>
    [Fact]
    public void TheSixthOfPagumeIsReachableInALeapYear()
    {
        var p = Of(2027, 9, 11);   // 2019 E.C. is a leap year

        Assert.Equal(2019, p.Year);
        Assert.Equal(13, p.Month);
        Assert.Equal(6, p.Day);
    }

    // ---- continuity ------------------------------------------------------------------------

    /// <summary>
    /// ⚠️ Walking a year day by day must never skip, repeat or run backwards. An off-by-one at a
    /// month or year boundary is invisible in spot checks and obvious here.
    /// </summary>
    [Fact]
    public void EveryDayAcrossALeapBoundaryAdvancesExactlyOne()
    {
        var date = new DateTime(2026, 6, 1);
        var previous = EthiopianDate.FromGregorian(date);

        for (var i = 1; i < 800; i++)   // spans two Ethiopian new years, one of them a leap
        {
            var current = EthiopianDate.FromGregorian(date.AddDays(i));

            var advancedWithinMonth = current.Year == previous.Year
                && current.Month == previous.Month && current.Day == previous.Day + 1;
            var rolledToNextMonth = current.Year == previous.Year
                && current.Month == previous.Month + 1 && current.Day == 1
                && previous.Day == EthiopianDate.MonthLength(previous.Year, previous.Month);
            var rolledToNextYear = current.Year == previous.Year + 1
                && current.Month == 1 && current.Day == 1 && previous.Month == 13;

            Assert.True(advancedWithinMonth || rolledToNextMonth || rolledToNextYear,
                $"{previous.Year}-{previous.Month}-{previous.Day} → {current.Year}-{current.Month}-{current.Day}");

            previous = current;
        }
    }

    // ---- formatting --------------------------------------------------------------------------

    /// <summary>
    /// ⚠️ The era marker is not decoration. A bare "2002" printed beside a Gregorian "2010" in the
    /// next column reads as a typo; ዓ.ም says it is another calendar.
    /// </summary>
    [Fact]
    public void FormattingNamesTheMonthAndMarksTheEra()
    {
        var text = EthiopianDate.Format(new DateTime(2010, 1, 1));

        Assert.Equal("ታኅሣሥ 23, 2002 ዓ.ም", text);
    }

    [Fact]
    public void FormattingCanUseTransliteratedMonths()
    {
        Assert.Equal("Tahsas 23, 2002 E.C.", EthiopianDate.Format(new DateTime(2010, 1, 1), geez: false));
    }

    [Fact]
    public void BothMonthNameSetsCoverAllThirteenMonths()
    {
        Assert.Equal(13, EthiopianDate.MonthsGeez.Length);
        Assert.Equal(13, EthiopianDate.MonthsLatin.Length);
        Assert.All(EthiopianDate.MonthsGeez, m => Assert.False(string.IsNullOrWhiteSpace(m)));
    }
}
